### ISSUE TITLE
gulp-favicon replaced html file

### ISSUE THREAD

**Issue by WuglyakBolgoink** [evilebottnawi/favicons#132]
Hi,
In my config:

```
        html: '../../index.html',
        pipeHTML: true,
        replace: false,
```

if I start gulp-task - this task cleared my existing HTML file and put into this file generated array of meta-links....

Is it possible to append this array before `</head>`??? or any  other case to get snippet from gulp task?

Thanks!

**Comment by ArmorDarks** [comment]
You shouldn't write directly into html. Instead, use `cheerio` or anything other you like to append generated content.

**Comment by brunocodutra** [comment]
This is not relevant anymore on master, since writing to file is out of scope
