### ISSUE TITLE
SyntaxError: use of const in strict mode

### ISSUE THREAD

**Issue by Sizuko** [evilebottnawi/favicons#136]
Hi,

Since you merge with #135, i got this error.
It seems it comes from index.js file in to-ico package.

**Comment by evilebottnawi** [comment]
@Sizuko Thanks for feedback, what node version are you use?

**Comment by Sizuko** [comment]
I'm on 6.2.0

**Comment by evilebottnawi** [comment]
@Sizuko can't reproduce? Can you get more information about problem?

**Comment by evilebottnawi** [comment]
@Sizuko `toIco` not support 0.10 node, maybe best solution up version nodejs? If this is not possible, I see what you can do with it.

**Comment by Sizuko** [comment]
Here is a copy of the error that i get when i start my meteor app:

```
/Users/nicolasthomas/Documents/IconsGeneratorTests/.meteor/local/build/programs/server/packages/modules.js:109174
const parsePng = require('parse-png');
^^^^^
SyntaxError: Use of const in strict mode.
at /Users/nicolasthomas/Documents/IconsGeneratorTests/.meteor/local/build/programs/server/boot.js:292:30
at Array.forEach (native)
at Function._.each._.forEach (/Users/nicolasthomas/.meteor/packages/meteor-tool/.1.3.4.sbx0n2++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
at /Users/nicolasthomas/Documents/IconsGeneratorTests/.meteor/local/build/programs/server/boot.js:133:5
=> Exited with code: 8
```

**Comment by evilebottnawi** [comment]
@Sizuko what about up version node, i written this above?

**Comment by Sizuko** [comment]
For now i'm using meteor 1.3.4 which is using the version of node that i tell you but they are updating meteor to 1.4 and they are upgrading to node version 4.4.7
Don't know if it will fix it my error.

And for now until i know how to fix it i will continu to use favicon 4.7.1 that i used before updating.

**Comment by evilebottnawi** [comment]
@Sizuko good solution, i think we need docs about this.
/cc @haydenbleasel 
We will need write note in docs about support for old nodejs version users.

**Comment by Sizuko** [comment]
I'll make you know if meteor 1.4 fix my error.
Until then, thx for for fast reply @evilebottnawi

**Comment by haydenbleasel** [comment]
@Sizuko @evilebottnawi It's because `to-ico` is our only dependency written purely in ES6. So the answer is to get Node running on v5 or v6+ (with ES6 support) but I'd love if `to-ico` implemented an ES5 version like `Favicons` does.

**Comment by evilebottnawi** [comment]
@haydenbleasel we can do PR

**Comment by haydenbleasel** [comment]
@evilebottnawi Yeah it should be easy, just need a gulpfile like this repo with Babel.

**Comment by evilebottnawi** [comment]
@haydenbleasel i create issue, let's wait what say @kevva

**Comment by kevva** [comment]
`0.10` is only maintained until October and `0.12` until December. I suggest upgrading to v4 or v6.

**Comment by brunocodutra** [comment]
It's been 18 months and even node 4 is about to reach EOL.
