### ISSUE TITLE
White background for apple- prefixed icons

### ISSUE THREAD

**Issue by ryanhomer** [evilebottnawi/favicons#173]
I have a transparent PNG that I'm using to generate all my icons. All the `apple-touch` prefixed icons that are generated have a white background. Why is this? Is this following some Apple guideline? I'm mostly interested in generating these icons for Safari. Is there a way to preserve the transparency for these icons? Thanks in advance.

**Comment by dangreen** [comment]
@ryanhomer `apple-touch` icons are used when you add site/webapp to homescreen. Icons for iOS must have a background.
https://developer.apple.com/ios/human-interface-guidelines/graphics/app-icon/
