### ISSUE TITLE
Looking for a new owner of this project

### ISSUE THREAD

**Issue by haydenbleasel** [evilebottnawi/favicons#180]
@jantimon @evilebottnawi @dangreen maybe you guys would be interested?

**Comment by haydenbleasel** [comment]
@jessehattabaugh @chaffeqa @jessaustin @tlvince @brianberlin

**Comment by dangreen** [comment]
@haydenbleasel If no one wonts, then I can.

**Comment by evilebottnawi** [comment]
@haydenbleasel i can

**Comment by chaffeqa** [comment]
You could make a new org, and give users ownership

**Comment by haydenbleasel** [comment]
@evilebottnawi I can transfer it to you but you need to delete your fork first.

**Comment by evilebottnawi** [comment]
@haydenbleasel doing

**Comment by haydenbleasel** [comment]
@evilebottnawi Great, you should get an email now.

**Comment by evilebottnawi** [comment]
@haydenbleasel thanks! done :+1: In near future i will try to close the main problems that have accumulated.

Please ping me if someone can help me with this.

**Comment by dangreen** [comment]
@evilebottnawi I will gladly help 😃

**Comment by evilebottnawi** [comment]
@dangreen invite has been sent

**Comment by haydenbleasel** [comment]
Hey @evilebottnawi you'll need an NPM account so I can tranfer you admin privileges to publish

**Comment by evilebottnawi** [comment]
@haydenbleasel https://www.npmjs.com/~evilebottnawi

**Comment by haydenbleasel** [comment]
Great, all done!
