### ISSUE TITLE
Double slashes in URLs get swallowed

### ISSUE THREAD

**Issue by alaz** [evilebottnawi/favicons#182]
I am specifying a CDN server in `path` option, e.g.

```
path: 'https://assets.server/path',
```

The problem is that the resulting HTML file contains malformed URLs like in the following fragment:

```
<link rel="apple-touch-icon" sizes="76x76" href="https:/assets.server/path/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="https:/assets.server/path/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="https:/assets.server/path/apple-touch-icon-120x120.png">
```

**Comment by alaz** [comment]
Ah, I found #116. Mine version of "favicons" is 2.2.7:

```
$ yarn list gulp-favicons
yarn list v0.24.6
└─ gulp-favicons@2.2.7
✨  Done in 1.02s.
```

**Comment by levibuzolic** [comment]
Hit this bug too, cause is here:

https://github.com/evilebottnawi/favicons/blob/4f6e8bd19115c2b0067e28f9df349905aea2d814/helpers.js#L45

Should maybe consider not using `path.join()` as it's not appropriate for joining web URLs -- `path.join` is designed to overcome inconsistencies in directory separators in OSs. I'll see if I can put up a PR.

**Comment by davidhellmann** [comment]
Hm any news here? Have the same problem :/
