### ISSUE TITLE
RFG now only uses https

### ISSUE THREAD

**Issue by GheloAce** [evilebottnawi/favicons#187]
I just noticed that the URL `http://realfavicongenerator.net/api/favicon` now redirects to `https`. Hence, whenever i try to run my gulp script i get, as an error:

```
TypeError: Cannot read property 'result' of undefined
```

Looking at the response, it returned the status code 301.  Changing [line 467](https://github.com/evilebottnawi/favicons/blob/4f6e8bd19115c2b0067e28f9df349905aea2d814/helpers-es5.js#L467) http to https make everything work.

I'll make a PR in awhile.

**Comment by tomyam1** [comment]
Here is a monkey patching script to fix the URL for now.
Add this before the require of favicons
```
// Monkey patching to fix the URL of realfavicongenerator
// until https://github.com/evilebottnawi/favicons/pull/188 is merged
const NodeRestClient = require('node-rest-client');
const origClient = NodeRestClient.Client;
NodeRestClient.Client = function () {
    const client = new origClient(arguments[0], arguments[1], arguments[2]);

    const origPost = client.post;
    client.post = function (url) {
        if (url === 'http://realfavicongenerator.net/api/favicon') {
            console.log('Monkey patching: using HTTPS url of realfavicongenerator')
            arguments[0] = 'https://realfavicongenerator.net/api/favicon';
        }
        return origPost.apply(this, arguments);
    };

    return client;
};

```

**Comment by evilebottnawi** [comment]
We drop support RFG in new major version.
